### ISSUE TITLE
Chicaggo committees are a borked on the server.

### ISSUE THREAD

**Issue by fgregg** [opencivicdata/api.opencivicdata.org#14]
```
Traceback (most recent call last):
  File "/usr/local/bin/pupa", line 9, in <module>
    load_entry_point('pupa==0.4.1', 'console_scripts', 'pupa')()
  File "/pupa/src/pupa/pupa/cli/__main__.py", line 71, in main
    subcommands[args.subcommand].handle(args, other)
  File "/pupa/src/pupa/pupa/cli/commands/update.py", line 244, in handle
    report['import'] = self.do_import(juris, args)
  File "/pupa/src/pupa/pupa/cli/commands/update.py", line 177, in do_import
    report.update(bill_importer.import_directory(datadir))
  File "/pupa/src/pupa/pupa/importers/base.py", line 169, in import_directory
    return self.import_data(json_stream())
  File "/pupa/src/pupa/pupa/importers/base.py", line 206, in import_data
    obj_id, what = self.import_item(data)
  File "/pupa/src/pupa/pupa/importers/base.py", line 226, in import_item
    data = self.prepare_for_db(data)
  File "/pupa/src/pupa/pupa/importers/bills.py", line 60, in prepare_for_db
    action['organization_id'])
  File "/pupa/src/pupa/pupa/importers/base.py", line 147, in resolve_json_id
    self.model_class.__name__, json_id))
pupa.exceptions.UnresolvedIdError: multiple objects returned for pseudo id to Organization: ~{"name": "Committee on Transportation and Public Way"}
```

Could you run: https://gist.github.com/fgregg/7bc8ccb4d9603b6db3f7#file-committee-sql This should fix the problem.

**Comment by jpmckinney** [comment]
Closing as the API at this URL is gone.
